# (PART) Study 1 {-}

# Libraries, settings, and custom functions

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE, 
  warning = FALSE, 
  cache = TRUE
  )
```

In this online book, we document all steps from raw data to final analysis for [Project title].

First, we load the libraries we'll be using.
The `pacman` package helps with package management.
```{r load-libraries}
if (!requireNamespace("pacman"))
  install.packages("pacman")

library(pacman)

p_load(
  here,
  usethis,
  readxl,
  lubridate,
  anytime,
  patchwork,
  scales,
  ggthemr,
  naniar,
  visdat,
  tidyverse,
  parameters
)
```

Next, some options.
```{r options}
set.seed(42)
```

Custom functions that we'll be using throughout this online book.
```{r custom-functions}
read_both_waves <- function(stub = "OII_PVZ_Authentications", ...) {
  # Filenames of wave 1 and 2 authentications files
  list.files(
    "data-raw/ea", pattern = stub, full.names = TRUE
  ) %>% 
    # Put wave 1 first
    rev() %>% 
    # Read into a list of data frames
    map(read_csv, ...) %>% 
    # Bind into one data frame with wave ID
    bind_rows(.id = "wave") %>%
    # Take only participants who filled out survey
    filter(player_id %in% survey_ids)
}

edafig <- function(x, y) {
  pvz_bfn %>% 
    ggplot(aes({{x}}, {{y}})) +
    scale_y_continuous(breaks = pretty_breaks()) +
    geom_smooth(method = "lm", fill="#0072B2", color="#0072B2", alpha = .2) +
    geom_point(color = "#56B4E9", alpha = 0.5) +
    theme(aspect.ratio = 1)
}

foo <- function(x, y) {
  ggplot(pvz_bfn, aes({{x}}, {{y}})) +
    geom_blank() +
    geom_point(col = "navy", fill = "white", shape = 21, stroke = 1) +
    scale_y_continuous(breaks = 1:7, labels = labels) +
    theme(plot.margin = unit(c(5,5,5,5), "mm"))
}

lm_function <- 
  function(
    data, 
    mapping, 
    ...
    ){
  p <- 
    ggplot(
      data = data, 
      mapping = mapping
      ) + 
    geom_point(
      color = "#56B4E9",
      alpha = 0.5
    ) + 
    geom_smooth(
      method=lm, 
      fill="#0072B2", 
      color="#0072B2", 
      ...)
  p
}

dens_function <-
  function(
    data,
    mapping,
    ...
  ){
    p <- 
      ggplot(
        data = data,
        mapping = mapping
      ) +
      geom_density(fill = "#009E73", color = NA, alpha = 0.5)
  }

pair_plot <- 
  function(
    dat
  ) {
    GGally::ggpairs(
      data = dat,
      lower = list(continuous = lm_function), # custom helper function
      diag = list(continuous = dens_function), # custom helper function
    ) +
      theme(
        axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(),
        strip.background = element_blank()
      )
  }
```

