# Analyses

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = TRUE,
  warning = FALSE,
  message = FALSE,
  # Save png and pdf figures
  dev = c("png", "pdf"),
  fig.ext = c("png", "pdf")
)
```

```{r}
library(pacman)
p_load(
  here,
  knitr,
  patchwork,
  scales,
  parameters,
  ggstance,
  tidyverse
)
```


```{r}
game_time <- read_rds(here("data/ea/game_time.rds"))
leveling <- read_rds(here("data/ea/leveling.rds"))
xp <- read_rds(here("data/ea/xp.rds"))
gestures <- read_rds(here("data/ea/gestures.rds"))
prestige <- read_rds(here("data/ea/prestige.rds"))
friends <- read_rds(here("data/ea/friends.rds"))
pvz <- read_rds(here("data/ea/pvz_bfn.rds"))
```

## Preface

## RQ1: Time and well-being

### Objective vs subjective game time

```{r}
pvz <- mutate(pvz, Hours_est = active_play_hours + active_play_minutes/60)
p0 <- pvz %>% 
  ggplot(aes(Hours, Hours_est)) +
  geom_point(shape = 1, alpha = .5, size = .5) +
  scale_y_continuous(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  geom_smooth(method = "lm", col = "black", size = .5) +
  theme(aspect.ratio = 1)
p0 + geom_abline(lty = 2, size = .25)
# z score of that one player's time
max(scale(pvz$Hours), na.rm = TRUE)
```

We take out that player from analyses related to objective game time because the game time is suspect and game time measures are noisy

```{r}
excessive_gamer <- pvz %>% 
  filter(Hours > 140) %>% 
  pull(player_id)
p0 <- p0 %+% 
  (p0$data %>% filter(player_id != excessive_gamer))
```

```{r}
p1 <- p0 +
  geom_abline(lty = 2, size = .25, col = "black")
p1
```

```{r}
x1 <- lm(Hours_est ~ Hours, data = p0$data)
parameters(x1) %>% kable(digits = 3)
parameters(x1, standardize = 'refit') %>% kable(digits = 3)
```

### Objective time and SWB

```{r}
p2 <- p0 + aes(y = spane_balance)
p2
```

```{r}
x2 <- lm(spane_balance ~ Hours, data = p0$data)
parameters(x2) %>% kable(digits = 3)
parameters(x2, standardize = 'refit') %>% kable(digits = 3)
```

### Subjective time and SWB

```{r}
p3 <- p0 + aes(x = Hours_est, y = spane_balance)
p3
```

```{r}
x3 <- lm(spane_balance ~ Hours_est, data = p0$data)
parameters(x3) %>% 
  kable(digits = 3)
parameters(x3, standardize = 'refit') %>% 
  kable(digits = 3)
```

### Figure

```{r rq1-figure, fig.height = 2.8}
(p1 + labs(x = "Hours played", y = "Estimated hours") | 
  p2 + labs(x = "Hours played", y = "Affective well-being") | 
  p3 + labs(x = "Estimated hours", y = "Affective well-being")) +
  plot_annotation(tag_levels = "A")
```

## RQ2: Well-being and motivation

```{r}
rq2 <- pvz %>% 
  select(spane_balance, autonomy, competence, relatedness, enjoyment, extrinsic, Hours) %>% 
  filter(Hours < 140) %>% 
  mutate(Hours = Hours / 10)
  
# Nice names for plots
rq2 <- rq2 %>% rename_all(str_to_title)

psych::cor.plot(
  rq2, scale = FALSE, stars = TRUE, xlas = 2, show.legend = FALSE
)

# Standardize everything but Hours
rq2 <- rq2 %>% 
  mutate(across(Spane_balance:Extrinsic, ~as.numeric(scale(., T, T))))

# Omnibus model with all variables
x <- lm(
  Spane_balance ~ (Autonomy + Competence + Relatedness + Enjoyment + Extrinsic) * Hours, 
  data = rq2
  )
# Models for individual variables
x1 <- lm(
  Spane_balance ~ (Autonomy) * Hours, 
  data = rq2
  )
x2 <- lm(
  Spane_balance ~ (Competence) * Hours, 
  data = rq2
  )
x3 <- lm(
  Spane_balance ~ (Relatedness) * Hours, 
  data = rq2
  )
x4 <- lm(
  Spane_balance ~ (Enjoyment) * Hours, 
  data = rq2
  )
x5 <- lm(
  Spane_balance ~ (Extrinsic) * Hours, 
  data = rq2
  )
```

```{r rq2-figure, fig.height = 3}
# Put it all together in one plot
map(list(x, x1, x2, x3, x4, x5), ~as_tibble(parameters(.))) %>% 
  bind_rows(.id = 'Model') %>% 
  mutate(Model = ifelse(Model==1, 'Omnibus', 'Unique')) %>% 
  filter(!(Parameter %in% c('(Intercept)'))) %>%
  mutate(Parameter = fct_rev(fct_inorder(Parameter))) %>% 
  ggplot(aes(Coefficient, Parameter, col = Model)) +
  scale_x_continuous('Standardized coefficient', breaks = pretty_breaks()) +
  geom_vline(xintercept = 0, lty = 2, size = .25) +
  geom_pointrangeh(
    aes(xmin = CI_low, xmax = CI_high), 
    size = .4, position = position_dodgev(.25)
    ) +
  theme(axis.title.y = element_blank())

last_plot() %+% (last_plot()$data %>% filter(Model=='Omnibus')) + aes(col=NULL)
```
